# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$hostname\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

add_newline = false

[directory]
style = "green"
truncation_length = 1
#truncation_symbol = ".../"
fish_style_pwd_dir_length = 1

[character]
success_symbol = '[\$](green)' # "[❯](green)"
error_symbol = '[\$](red)'     # "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
ssh_only = false
# Trigger the hostname to show when in an ssh connection or toolbx container
detect_env_vars = ['SSH_CONNECTION', 'TOOLBOX_PATH']
format = '[@](bright-black)[$hostname](dimmed cyan) '
# Add the Nerd Font ssh symbol TODO: Make nerd fonts work
# ssh_symbol = " "
# format = '[$ssh_symbol](dimmed cyan) [on](bright-black) [$hostname](dimmed cyan) '

[cmd_duration]
format = "[$duration]($style) "
show_milliseconds = true
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
